.PHONY: all test test-fuzz test-production test-soak test-soak-netem web-assets web-assets-force docker docker-test linux windows darwin linux-i386 linux-amd64 linux-arm linux-arm64 windows-i386 windows-amd64 windows-arm64 darwin-amd64 darwin-arm64

WEBMANAGER_DIR := webmanager
WEB_NODE_MODULES := $(WEBMANAGER_DIR)/node_modules/.package-lock.json
WEB_BUILD_DIR := $(WEBMANAGER_DIR)/dist/webmanager/browser
WEB_BUILD_INDEX := $(WEB_BUILD_DIR)/index.html
WEB_EMBED_DIR := internal/assets/browser
WEB_EMBED_INDEX := $(WEB_EMBED_DIR)/index.html
DOCKER ?= docker
DOCKER_IMAGE ?= engarde:local
DOCKER_VERSION ?= local
WEB_BUILD_INPUTS := $(shell find $(WEBMANAGER_DIR)/src \( -type f -o -type d \) -print) \
	$(WEBMANAGER_DIR)/angular.json \
	$(WEBMANAGER_DIR)/tsconfig.json \
	$(WEBMANAGER_DIR)/.browserslistrc

all: linux windows darwin

test:
	go test -count=1 ./...

test-fuzz:
	ENGARDE_FUZZ_TIME="$${ENGARDE_FUZZ_TIME:-$${FUZZ_TIME:-5s}}" ./build-scripts/test-fuzz.sh

test-production:
	ENGARDE_STRESS_COUNT="$${ENGARDE_STRESS_COUNT:-10}" ENGARDE_FUZZ_TIME="$${ENGARDE_FUZZ_TIME:-5s}" ./build-scripts/test-production.sh

test-soak:
	ENGARDE_SOAK_DURATION="$${ENGARDE_SOAK_DURATION:-$${SOAK_DURATION:-10m}}" \
	ENGARDE_SOAK_TIMEOUT="$${ENGARDE_SOAK_TIMEOUT:-$${SOAK_TIMEOUT:-15m}}" \
	ENGARDE_SOAK_RACE="$${ENGARDE_SOAK_RACE:-$${SOAK_RACE:-0}}" \
	./build-scripts/test-soak.sh

test-soak-netem:
	ENGARDE_SOAK_DURATION="$${ENGARDE_SOAK_DURATION:-$${SOAK_DURATION:-10m}}" \
	ENGARDE_SOAK_TIMEOUT="$${ENGARDE_SOAK_TIMEOUT:-$${SOAK_TIMEOUT:-15m}}" \
	ENGARDE_SOAK_RACE="$${ENGARDE_SOAK_RACE:-$${SOAK_RACE:-1}}" \
	./build-scripts/test-soak-netem.sh

web-assets: $(WEB_EMBED_INDEX)

$(WEB_NODE_MODULES): $(WEBMANAGER_DIR)/package.json $(WEBMANAGER_DIR)/package-lock.json
	cd $(WEBMANAGER_DIR) && npm ci

$(WEB_BUILD_INDEX): $(WEB_NODE_MODULES) $(WEB_BUILD_INPUTS)
	cd $(WEBMANAGER_DIR) && npm run build-prod

$(WEB_EMBED_INDEX): $(WEB_BUILD_INDEX)
	@set -eu; \
		tmp="internal/assets/.browser.$$$$"; \
		trap 'rm -rf "$$tmp"' 0 1 2 3 15; \
		rm -rf "$$tmp"; \
		cp -r $(WEB_BUILD_DIR) "$$tmp"; \
		printf '%s\n' 'Generated by make web-assets. Keep this file so //go:embed has a directory in clean checkouts.' > "$$tmp/README.md"; \
		rm -rf $(WEB_EMBED_DIR); \
		mv "$$tmp" $(WEB_EMBED_DIR); \
		trap - 0 1 2 3 15

web-assets-force:
	rm -rf $(WEB_BUILD_DIR)
	$(MAKE) web-assets

docker:
	$(DOCKER) build --build-arg VERSION="$(DOCKER_VERSION)" --tag "$(DOCKER_IMAGE)" .

docker-test: docker
	@set -eu; \
		user="$$( $(DOCKER) image inspect --format '{{.Config.User}}' "$(DOCKER_IMAGE)" )"; \
		test "$$user" = "65532:65532"; \
		$(DOCKER) run --rm "$(DOCKER_IMAGE)" -v; \
		name="engarde-server-smoke-$$$$"; \
		trap '$(DOCKER) rm --force "$$name" >/dev/null 2>&1 || true' 0 1 2 3 15; \
		$(DOCKER) run --detach --name "$$name" --network none \
			--read-only --cap-drop ALL \
			--mount type=bind,src="$(abspath examples/config/tcp-socks5-server.yml)",dst=/etc/engarde/engarde.yml,readonly \
			"$(DOCKER_IMAGE)" >/dev/null; \
		sleep 1; \
		if test "$$( $(DOCKER) inspect --format '{{.State.Running}}' "$$name" )" != "true"; then \
			$(DOCKER) logs "$$name"; \
			exit 1; \
		fi; \
		$(DOCKER) rm --force "$$name" >/dev/null; \
		trap - 0 1 2 3 15

linux-i386: $(WEB_EMBED_INDEX)
	CGO_ENABLED=0 GOOS=linux GOARCH=386 ./build-scripts/build.sh
linux-amd64: $(WEB_EMBED_INDEX)
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 ./build-scripts/build.sh
linux-arm: $(WEB_EMBED_INDEX)
	CGO_ENABLED=0 GOOS=linux GOARCH=arm ./build-scripts/build.sh
linux-arm64: $(WEB_EMBED_INDEX)
	CGO_ENABLED=0 GOOS=linux GOARCH=arm64 ./build-scripts/build.sh
windows-i386: $(WEB_EMBED_INDEX)
	GOOS=windows GOARCH=386 ./build-scripts/build.sh
windows-amd64: $(WEB_EMBED_INDEX)
	GOOS=windows GOARCH=amd64 ./build-scripts/build.sh
windows-arm64: $(WEB_EMBED_INDEX)
	GOOS=windows GOARCH=arm64 ./build-scripts/build.sh
darwin-amd64: $(WEB_EMBED_INDEX)
	GOOS=darwin GOARCH=amd64 ./build-scripts/build.sh
darwin-arm64: $(WEB_EMBED_INDEX)
	GOOS=darwin GOARCH=arm64 ./build-scripts/build.sh

linux: linux-i386 linux-amd64 linux-arm linux-arm64
windows: windows-i386 windows-amd64 windows-arm64
darwin: darwin-amd64 darwin-arm64
